### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by achrafkh** [stevebauman/administration#6]
i did everything as u said, i got serviceprovider not found (Orchestra/html)
i added serviceprovider  but i got this probleme

ReflectionException in Container.php line 738:
Class admin.setup does not exist

i have laravel 5.2 ,

**Comment by stevebauman** [comment]
Are you caching your routes? Try clearing it using `php artisan route:clear`. Also that's strange you receive the error for orchestra/html. The service provider is automatically registered by the `App\Providers\HtmlServiceProvider`.

**Comment by stevebauman** [comment]
Apologies, there was an issue with the installation process I have in the readme. It's corrected now. Give it a shot!

**Comment by achrafkh** [comment]
u have a typo (php artisan)
also mention 'php artisan migrate'

still getting  this
UnauthorizedException in SetupMiddleware.php

**Comment by stevebauman** [comment]
Yup you're right. Also do you have any users in your database? If so, this is intended because the setup is only accessible when no users exist yet.

**Comment by achrafkh** [comment]
u need to mention that collective html should be removed from app.php
i made the setup but when i login i get this

BadMethodCallException in Builder.php line 2161:
Call to undefined method Illuminate\Database\Query\Builder::hasPermission()

**Comment by stevebauman** [comment]
You need to insert the `Stevebauman\Authorization\Traits\UserRolesTrait` onto your User model. I'm still working on documentation.
